version: "2"
services:
  web:
    build: .
    links: 
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    depends_on:
      - db
  db:
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./data/mongo:/data/db
volumes:
  mongodata:
